import "./globals.css";
import { Inter } from "next/font/google";
import RootStyleRegistry from "@/components/RootStyleRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Header</div>
        <RootStyleRegistry>{children}</RootStyleRegistry>
        <div>Footer</div>
      </body>
    </html>
  );
}
